### ISSUE TITLE
Should Hydra::Works be an Engine

### ISSUE THREAD

**Issue by jeremyf** [projecthydra-labs/hydra-works#1]
Given that Hydra::Works is a modeling exercise, do we need the verbosity of a Rails engine? The Rails engine requires continual rebuilding of a dummy application.

It could instead be a Railtie. Or a gem that leverages ActiveSupport and ActiveModel.

**Comment by flyingzumwalt** [comment]
@jeremyf I'm tempted to pull the CurationConcern pattern (mainly routing, views, controllers & actors) from Curate/Worthwhile into a hydra-works engine.  This would allow anyone to create custom work types with custom workflows in any Hydra head.  Underneath it would use hydra-works-models to model Works & Files as PCDM objects & PCDM files.  

Thoughts?

**Comment by jpstroop** [comment]
:+1: (as you know)

**Comment by jeremyf** [comment]
:+1:

**Comment by flyingzumwalt** [comment]
Ok.  This is officially out of scope for the current sprint, but the Princeton team might be able to proffer a sample version of this engine in about a week.  It will be a stripped-down version of projecthydra-labs/worthwhile with 

- Only functionality that is relevant to the Curation Concern pattern (routing, views, controllers & actors)
- Namespaces updated to use Hydra::Works instead of Worthwhile
- Models refactored to rely on the current code evolving in projecthydra-labs/hydra-works (and in a hydra-works-models directory instead of worthwhile-models

**Comment by flyingzumwalt** [comment]
@jeremyf do you know if there are new developments in curate that evolved since we forked worthwhile that should find their way into this engine?

**Comment by jeremyf** [comment]
@flyingzumwalt There are new developments in Curate regarding the CurationConcern pattern.

However, I am steering very far of the entire ActiveRecord pattern for Repository objects going forward. The work on [Sipity](https://github.com/ndlib/sipity) is the front-end for our user facing ingest (and workflow). Our [ROF](https://github.com/ndlib/rof) gem is how we are throwing things into Fedora.

The fundamental concept of leveraging the same model for create, read, and update is proving to be very expensive in application maintenance and data management maintenance over time.

At HydraConnect I will be further articulating my vision and the steps we are taking.

**Comment by flyingzumwalt** [comment]
@jeremyf Regarding the new developments in Curate around the CurationConcern pattern, I'm tempted to set up this sample code base derived from worthwhile and then update it to incorporate improvements from curate.  Does that sound like a good path to you?

I look forward to seeing your presentation about Sipity and ROF at HydraConnect.  I suspect that anything we do to encourage convergence of other code bases around hydra-works will make it easier to present adoption paths for embracing your innovations, even if the hydra-works engine uses Rails patterns for now.  Do you agree?

**Comment by jeremyf** [comment]
@flyingzumwalt The convergence around hydra-works is good, however I believe the long term path forward is separation of application concerns regarding Create, Edit, Discover, and Show. I'm not paying attention to Hydra::Works at this point as I have to focus on our institution concerns. But consider:

* ND's rules for Create are complicated compared to the Sufia rules
* However our rules for Discovery and Show are similar
* ND's rules for Edit are more complicated that Sufia as well.

So to conflate those concerns within the same application means numerous inflection points and configuration that may or may not be applicable.

We will be porting our Curate data model and architecture to Sipity for ingest. So there will be a path forward.

**Comment by flyingzumwalt** [comment]
:+1:

**Comment by flyingzumwalt** [comment]
Closing this ticket, noting the discussion for the coming weeks' work.
