### ISSUE TITLE
Service: attach file to work

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#103]
Looking for the necessary services for adding an uploaded file to a Work.  This will ultimately be used by methods like Sufia [GenericWorkActor](https://github.com/projecthydra/sufia/blob/pcdm/sufia-models/app/actors/curation_concern/generic_work_actor.rb#L73-L83) `.attach_file`  I suspect that it breaks down into a number of Services that will be called in succession, possibly by a AttachFileToWork service?

* Create the GenericFile object from upload (possibly using  CreateFileWithUpload service from #78)
* Add the GenericFile to the work (possibly using a AddFileToWork service?)

**Comment by flyingzumwalt** [comment]
FYI: That method is originally from https://github.com/projecthydra-labs/worthwhile/blob/master/worthwhile-models/app/actors/curation_concern/generic_work_actor.rb#L78-L86 -- a slightly clearer implementation.

**Comment by grosscol** [comment]
I was looking at this as well, and created #118 to address the difference in call signatures.  Where hydra works expected at path which would subsequently be used with File.open, and the calling implementations (e.g. Sufia GenericWorkActor) expected to pass a file.

**Comment by escowles** [comment]
In light of the move away from atomic service objects and towards models with internal validation, should we close this?  Or is bundling two or three calls a worthwhile service?

**Comment by grosscol** [comment]
If a downstream application, like curation concerns, wanted to enable doing this all at once, couldn't that application define an actor for it there?  The application might want to do something in between uploading the file to the GenericFile and attaching the GenericFile to the GenericWork.

**Comment by flyingzumwalt** [comment]
I think skip it.

**Comment by flyingzumwalt** [comment]
Clarification: I think it's fine to skip creating this service. The existing code is sufficient.  When I wrote this ticket, we didn't have all of the relationship/aggregation setters so it was much less clear how to do this.
