### ISSUE TITLE
Bug: GenericWork and GenericFile are incompatible with ActiveFedora::Base.load_instance_from_solr

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#107]
This came up in Sufia's [CopyPermissionsJob on line 13](https://github.com/projecthydra/sufia/blob/pcdm/sufia-models/app/jobs/copy_permissions_job.rb#L13) (originally from Worthwhile) where it uses ActiveFedora::Base.load_instance_from_solr to load a GenericWork and then iterates over its `.generic_files`.

See associated PR #108 for example failure.

**Comment by jcoyne** [comment]
closed by https://github.com/projecthydra/active_fedora/pull/804
