### ISSUE TITLE
BUG: solrize fails with "does not respond to `include?`"

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#109]
In add_collection_spec, test 'should solrize member ids' fails
```
expect(subject.to_solr["generic_works_ssim"]).to include(generic_work1.id,generic_work2.id)
expect(subject.to_solr["generic_works_ssim"]).not_to include(collection2.id,collection1.id,collection3.id)
expect(subject.to_solr["collections_ssim"]).to include(collection2.id,collection1.id,collection3.id)
expect(subject.to_solr["collections_ssim"]).not_to include(generic_work1.id,generic_work2.id)
```
This code was copied from pcdm tests.  Only the test was copied.  It could be that some additional setup is required for to_solr method to work properly.

Similar tests fail in each of the Add services.

**Comment by elrayle** [comment]
In AddGenericFileToGenericFile and AddRelatedObjectToGenericFile, to_solr is also checked for files.  I'm not sure pcdm files are going to be indexed in solr.

**Comment by jcoyne** [comment]
I think this is done in projecthydra/active_fedora#806. @elrayle can you confirm/close this issue?

**Comment by terrellt** [comment]
This is a bug with generic_works not being indexed.

**Comment by terrellt** [comment]
Closed by https://github.com/projecthydra-labs/hydra-pcdm/pull/164
