### ISSUE TITLE
Use Case: Research Dataset

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/hydra-works#11]
A research dataset containing a set of files organized into top-level categories of preparatory materials, raw data files, statistics, and visualization images, with multiple files in each category.  The visualization images are further organized in a hierarchy by type, and then by X/Y/Z axis.

* The dataset as a whole has descriptive metadata describing the research project, the research team, etc.
* The top-level categories and the hierarchy of visualization images have titles.
* Each individual file has a title and technical metadata.

**Comment by flyingzumwalt** [comment]
Did the lessons & ideas from this thread make it into some other documentation or specs?   Can we close this ticket?

**Comment by escowles** [comment]
Yes, I think the info in this thread informed the discussions in Portland and the subsequent documentation, so this ticket can be closed.
