### ISSUE TITLE
service object: MoveGenericWorkToCollection

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#119]
See code for issue https://github.com/projecthydra-labs/hydra-works/issues/76.  Create the new service MoveGenericWorkToCollection in the same way MoveGenericFileToGenericWork is implemented.

Code and Tests for MoveGenericFileToGenericWork:
https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/services/generic_work/move_generic_file.rb
https://github.com/projecthydra-labs/hydra-works/blob/master/spec/hydra/works/services/generic_work/move_generic_file_spec.rb

**Comment by elrayle** [comment]
Even though Add and Remove services will do validation, probably should do validation in this service to be sure that before we try to make any adjustments that all the passed in parameters are valid.  Otherwise, Add could pass and Remove could fail causing an uncertain state.

**Comment by grosscol** [comment]
Is this still valid now that we're moving away from service objects?

**Comment by grosscol** [comment]
`members=` from #232
