### ISSUE TITLE
Provide a sample use case or template

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hydra-works#12]
We would do well to provide at least one sample use case, or a use case template, so that potential contributors know what we're looking for.  #9, #10, and #11 are quite different from one another.  Is that variation OK?  How much detail are we looking for, and how much do we care about how they're formatted (we talked previously about user stories, and we're talking now about use cases, and these are different and equally useful things).

**Comment by flyingzumwalt** [comment]
Can we close this ticket?  Are there any action items?

**Comment by jpstroop** [comment]
The conversation may have migrated elsewhere, but the ultimate result (whether we came up with a template or just started copying each other) is the contents of the [use-cases](https://github.com/projecthydra-labs/hydra-works/tree/f1c6f2a40b0afacfc5ad28e5a260f0910e0104b7/use-cases) directory in this repo.
