### ISSUE TITLE
A GenericFile can find the GenericWorks that contain it

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#128]
In other words, a PCDM Object can find the Objects and Collections that contain it.

You might be able to do this with a has_many association.  Otherwise, see https://github.com/projecthydra-labs/activefedora-aggregation/tree/aggregated_by

This was blocked by projecthydra-labs/activefedora-aggregation#39

**Comment by grosscol** [comment]
Provided by `in_works` method
