### ISSUE TITLE
extremely slow AddFileToGenericFile service

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#129]
The Works:: AddFileToGenericFile service is extremely slow.
Any code that relies on Hydra::Works (ie. curation_concerns, sufia, etc.) ends up calling this service a lot.    Speeding it up will have a big impact on the runtime for downstream test suites, etc.

**Comment by jcoyne** [comment]
This module doesn't exist anymore, so closing.
