### ISSUE TITLE
PersistDerivativesOutputFile Service

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#130]
Implement Hydra::Works::PersistDerivativesOutputFile service

* `#call` conforms to the interface of hydra-derivatives PersistOutputFileService
* calls `Hydra::Works::AddFileToGenericFile` service

**Comment by mjgiarlo** [comment]
Implemented in #132.

**Comment by mjgiarlo** [comment]
This is mostly done, with some remaining work.  Closing this issue, and @flyingzumwalt will ticket the outstanding stuff.
