### ISSUE TITLE
UploadFile and AddFile services should accept mime_type keyword

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#136]
If I know what mime_type I want set on the file that I'm adding, I should be able to tell the service to use it.

I should be able to do this:
```ruby
Hydra::Works::UploadFileToGenericFile.call(generic_file,file.path, mime_type:"image/png")
expect(generic_file.reload.original_file.mime_type).to eq('image/png')
```

**Comment by flyingzumwalt** [comment]
... Same goes for original_name (ie. I provided a tempfile or an IOStream but I want the original_name to be set to something like `world.png`

**Comment by grosscol** [comment]
Completed.
