### ISSUE TITLE
Consider Removing #contains=

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/hydra-works#140]
https://github.com/projecthydra-labs/hydra-pcdm/blob/master/lib/hydra/pcdm/models/concerns/object_behavior.rb#L83-L88

**Comment by grosscol** [comment]
Should object= also be removed?  Is this in favor of using a service object to add files to the object?

**Comment by elrayle** [comment]
RE: objects=

@grosscol, we are moving toward removing the atomic service objects and replacing them with methods as proposed in https://github.com/projecthydra-labs/hydra-pcdm/wiki/Proposed-Interfaces#defining-an-aggregation-with-multiple-filters.

Related to this:
* [Proposed new API](https://github.com/projecthydra-labs/hydra-pcdm/wiki/Proposed-Interfaces)
* https://github.com/projecthydra-labs/activefedora-aggregation/issues/45
* https://github.com/projecthydra-labs/activefedora-aggregation/issues/44

**Comment by elrayle** [comment]
RE: contains=

It appears that this method is never used or tested.  Some exploration is required to confirm this.  If it is true, then we should be able to safely remove the contains= method.

**Comment by escowles** [comment]
Should we just deprecate contains= along with the service objects in https://github.com/projecthydra-labs/hydra-pcdm/pull/144, https://github.com/projecthydra-labs/hydra-pcdm/pull/158, and https://github.com/projecthydra-labs/hydra-works/pull/161?

**Comment by terrellt** [comment]
@escowles @elrayle Do we have a status here?

**Comment by escowles** [comment]
I don't have anything new here.  But I agree with @elrayle: it doens't look like this is being used or tested.  We're overriding it in Hydra::Works::GenericWorkBehavior to throw an error (and that's tested at least).  I don't see any usage of it in hydra-pcdm, hydra-works, or curation_concerns.

So I think we should remove it -- whether that's just removing it, deprecating it, etc.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by mjgiarlo** [comment]
Closed by PR.
