### ISSUE TITLE
Remove atomic service objects

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#155]
The following service objects are being replaced with the new API.

    AddXToY
    GetXFromY
    RemoveXFromY

Deprecate service objects with a target removal date.

See issue https://github.com/projecthydra-labs/hydra-pcdm/issues/142 for pcdm.

**Comment by elrayle** [comment]
Fixed by https://github.com/projecthydra-labs/hydra-works/pull/161

**Comment by grosscol** [comment]
Aside from the add file to generic file and upload file to generic file, these should all be gone.  Since add file to generic file is more involved, it might still be a reasonable plan to use a service object.
