### ISSUE TITLE
move deprecated service object tests to collection/generic_work/generic_file_spec tests

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#162]
Issue https://github.com/projecthydra-labs/hydra-works/issues/155 deprecated the atomic service objects. The tests were not moved or refactored as part of that process. Tests that continue to apply (most tests) need to be moved from the service object tests to models/collection_spec, generic_work_spec, or generic_file_spec, and updated to use direct method calls instead of service calls.

- [x] spec/hydra/works/services/collection/*
- [ ] spec/hydra/works/services/generic_file/*
- [ ] spec/hydra/works/services/generic_work/*

**Comment by escowles** [comment]
I added some checkboxes for the three categories of tests to refactor in this ticket.  I'll start with the collection tests, and the others are free if anyone wants to help out (cc: @grosscol)
