### ISSUE TITLE
07-31-2015 Remove deprecated methods associated with PR 155

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#163]
Search for DEPRECATION and remove any deprecated methods with a target date of 07-31-2015 or earlier.

**Comment by grosscol** [comment]
aggregates_collections.rb still has a non-deprecated child_collections_ids method.  It's a convenience method and the only method left in the AggregatesCollections module.  Not sure where this method should live or what the a better name for the module might be.

```Ruby
    def child_collection_ids
      child_collections.map(&:id)
    end
``` 

Perhaps collection_behavior.rb is a better place for it.  Thoughts?

**Comment by grosscol** [comment]
The get/add/remove related object calls are not deprecated, but this issue is being punted on until the resolution of #86.

**Comment by terrellt** [comment]
@grosscol If you remove that method you should still get child_collection_ids from the association readers.
