### ISSUE TITLE
Should generic_files be allowed to aggregate generic_files

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#165]
A philosophical question came up during a discussion for PR https://github.com/projecthydra-labs/hydra-works/pull/161 specifically asking whether a generic file should be allowed to aggregate other generic files.  

Conversion use case  (note: last image is the desired approach)
https://docs.google.com/document/d/1XQwQkXHIeZOc7gfxw-oTLPAuyHlTn9bLq6VgDCN8z3I/edit

Book with pages (note: generic_file for book aggregates pages, each of which is a generic_file)
https://docs.google.com/document/d/1FxYyhVkjIuvOq1d-MS2dzKTElIfNSk01ytwiAB5DZiw/edit

The book example is a common use case and our development team's preferred representation.

**Comment by jcoyne** [comment]
The book example doesn't make any sense to me. A GenericFile should be represent a single file. Like a PDF.  So I'd make a Book object aggregate Page objects (which could either extend GenericFile or have GenericFiles). The Page might also have a PDF object (which would probably extend GenericFile).  Am I off base here?  I don't see how a GenericFile would have anything under it besides NonRDFSources.

**Comment by jcoyne** [comment]
channeling @azaroth42

**Comment by azaroth42** [comment]
The semantics of GenericFile (notably a subclass of pcdm:Object) are completely opaque to me :confused:

**Comment by grosscol** [comment]
While PCDM allows for FileSets (formerly GenericFiles) to aggregate others, I was under the impression that HydraWorks was an opinionated subset of PCDM in which FileSets were the leaf PCDM::Objects.

**Comment by mjgiarlo** [comment]
Yes, that is right IMO that a FileSet is a model based on pcdm:Object that allows us to group related files together structurally, such as an uploaded file, its derivatives, blobs of generated XML (e.g., from characterization), a preservation master, and extracted full-text. IIRC -- **someone would do well to check my understanding here** -- we went the structural route because of the inability to (or inefficiencies with) relate/ing pcdm:Files to one another atop Fedora 4.

It would be good to hear from @elrayle if her understanding or thinking has changed since this issue was opened.

**Comment by terrellt** [comment]
Since the related files piece has a solution which doesn't involve another pcdm:object, then yes, :+1: to FileSets being the leaf.

**Comment by azaroth42** [comment]
Ditto :+1: to FileSets (thank you for renaming!) being leaf objects.

On Tue, Oct 6, 2015 at 3:01 PM, Trey Terrell <notifications@github.com>
wrote:

> Since the related files piece has a solution which doesn't involve another
> pcdm:object, then yes, [image: :+1:] to FileSets being the leaf.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthydra-labs/hydra-works/issues/165#issuecomment-146014952>
> .
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305
