### ISSUE TITLE
Hydra::Works::GenericFile should not have parent/child GenericFiles

### ISSUE THREAD

**Issue by escowles** [projecthydra-labs/hydra-works#170]
GenericFile should be a leaf node, that only contains pcdm:Files.  So there should not be a parent/child relationship between GenericFiles.

This ticket is to remove any definition of generic_file#child_generic_files and generic_file#parent_generic_file and related test coverage.

**Comment by atz** [comment]
Good.  This returns to the consensus I thought was well established previously.

**Comment by jpstroop** [comment]
:+1:

**Comment by jcoyne** [comment]
:+1:

**Comment by mjgiarlo** [comment]
:+1:
