### ISSUE TITLE
Accessing count or size of work.generic_files

### ISSUE THREAD

**Issue by tampakis** [projecthydra-labs/hydra-works#179]
In pinning Curation Concerns to the latest version of Hydra Works, a lot of specs fail related to calling .count and .size on work.generic_files.

When calling .count in [work_actor_spec](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/actors/curation_concerns/work_actor_spec.rb#L102) I get the following error:
```
Failure/Error: expect(curation_concern.generic_files.count).to eq 1
     RuntimeError:
       No :inverse_of or :predicate attribute was set or could be inferred for filter :generic_files on GenericWork
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_association.rb:336:in `find_reflection'
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_association.rb:291:in `construct_query'
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_association.rb:231:in `count'
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_proxy.rb:676:in `count'
     # ./spec/actors/curation_concerns/work_actor_spec.rb:102:in `block (6 levels) in <top (required)>'
```
When calling .size in [generic_work_spec](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/models/generic_work_spec.rb#L17) I get the following error:
```
     Failure/Error: expect(subject.generic_files.size).to eq 2
     NameError:
       undefined local variable or method `count_records' for #<ActiveFedora::Filter::Association:0x00000009ac8150>
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_association.rb:79:in `size'
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_proxy.rb:705:in `size'
     # ./spec/models/generic_work_spec.rb:17:in `block (3 levels) in <top (required)>'
```

I don't know if the inverse_of or predicate attributes are supposed to be defined, but a quick fix could be only calling `.size` on .generic_files and defining a count_records method in [active-fedora-aggregation](https://github.com/projecthydra-labs/activefedora-aggregation/blob/master/lib/active_fedora/filter/association.rb). Maybe something like this? 
```
  def count_records
    self.to_a.size
  end
```

**Comment by terrellt** [comment]
This should be fixed by https://github.com/projecthydra-labs/activefedora-aggregation/pull/68
