### ISSUE TITLE
Accessing generic_file.related_files

### ISSUE THREAD

**Issue by tampakis** [projecthydra-labs/hydra-works#180]
A generic_file is unable to access its related files. Running the [generic_file_spec](https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/models/generic_file_spec.rb#L197-L207) in Curation Concerns and calling generic_file.related_files gets this error:
```
     Failure/Error: subject { f1.reload.related_files }
     NoMethodError:
       private method `select' called for #<ActiveFedora::Filter::Association:0x00000008564980>
     # /home/nikitas/.rvm/gems/ruby-2.2.2@cc/bundler/gems/active_fedora-5466c650b7a3/lib/active_fedora/associations/collection_proxy.rb:115:in `select'
     # ./curation_concerns-models/app/models/concerns/curation_concerns/generic_file/belongs_to_works.rb:35:in `block in related_files'
     # ./curation_concerns-models/app/models/concerns/curation_concerns/generic_file/belongs_to_works.rb:35:in `each'
     # ./curation_concerns-models/app/models/concerns/curation_concerns/generic_file/belongs_to_works.rb:35:in `flat_map'
     # ./curation_concerns-models/app/models/concerns/curation_concerns/generic_file/belongs_to_works.rb:35:in `related_files'
     # ./spec/models/generic_file_spec.rb:201:in `block (4 levels) in <top (required)>'
     # ./spec/models/generic_file_spec.rb:203:in `block (4 levels) in <top (required)>'
```

**Comment by tampakis** [comment]
Looking at the [related_files method](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/generic_file/belongs_to_works.rb#L32-L36) in curation concerns shows that this issue is related to being unable to access work.generic_files like an array (kind of similar to #180).

**Comment by terrellt** [comment]
Yup, it looks like there's a #select in collection proxy, but not one for CollectionAssociation, so it's calling Object#select.

**Comment by terrellt** [comment]
Described by https://github.com/projecthydra/active_fedora/issues/609, and even has a pending test! @awead++

**Comment by terrellt** [comment]
I think https://github.com/projecthydra/active_fedora/pull/868 clears up this use case, but not projecthydra/active_fedora#609.

**Comment by tampakis** [comment]
:+1:
