### ISSUE TITLE
GenericWorks should have a .generic_file_ids= setter method

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#208]
I think this translates into a feature request for AF::Aggregation, but the request only makes sense with an example.  This is the example.

Use case: changing the order of generic_files within a generic_work
Currently I have to 
```ruby
page_ids = book.generic_file_ids
# {... rearrange page_ids ...}
book.member_ids = page_ids
```
I get an error if I try to call `book.generic_file_ids = page_ids`, even though that's where I got the ids.  

Note that generic_file_ids is a filtered subset of member_ids, so the code sample here actually risks accidentally removing other members from book.members.

Of course, I could always use member_ids for both getter and setter but that violates the whole reason for having the generic_file_ids method in the first place.

**Comment by flyingzumwalt** [comment]
Blocked by ctivefedora-aggregation#71

**Comment by jcoyne** [comment]
Keep in mind that the ids setter isn't going to get you much. It'll still have to do a find on each of the ids so that it can run the type_validator on each member.

**Comment by flyingzumwalt** [comment]
Ah.  So maybe it's a moot point for tomorrow's work.  I was hoping to avoid loading the objects before saving the new order.

**Comment by flyingzumwalt** [comment]
My use case is for reordering page images within books that sometimes have
hundreds of pages. Loading all of the member objects is not an option.

**Comment by jcoyne** [comment]
Yeah, I think you want to make a special function for that. Maybe `AggregationProxy#swap(i, j)`
