### ISSUE TITLE
Question regarding ICLA and asking for Use Cases via pull request

### ISSUE THREAD

**Issue by jeremyf** [projecthydra-labs/hydra-works#21]
Given that a few of the participants in the conversation haven't signed ICLAs, does it make sense that we use the pull request model for the code? This is documentation and brainstorming.

I'm a little unclear. Any ideas? @escowles

**Comment by flyingzumwalt** [comment]
Can we close this ticket?  Should this information be preserved somewhere?  Are there any action items or guidance that apply to the current sprint?
