### ISSUE TITLE
Can Hydra::Works::GenerateThumbnail go away?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#215]
It isn't used by CurationConcerns. CurationConcerns has https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/jobs/create_derivatives_job.rb which does the same.

**Comment by elrayle** [comment]
Observations...
* Hydra::Works::GenerateThumbnail does two things... 1) use object.build_thumbnail to hold the file, 2) call object.create_derivatives which is calling hydra:derivatives
* full text extraction is currently outside of hydra:derivatives, but will hopefully be moving there soon

Hydra::Works is meant to be the base of apps that may or may not use CurationConcerns.  The question should be, is there a generic approach that works for Hydra::Works that CurationConcerns could easily use.

See Issue https://github.com/projecthydra-labs/hydra-works/issues/220 for a discussion of moving full text extraction to hydra-derivatives.  The discussion there includes a discussion of a generalized approach for all derivatives which impacts the discussion here.

**Comment by jcoyne** [comment]
@elrayle Are there any known applications using GenerateThumbnail?  Secondly calling create_derivatives may create more than just a thumbnail, so GenerateThumbnail should be renamed to GenerateDerivatives or GenerateThumbnail should directly call `Hydra::Derivatives::ImageDerivatives.create()`

**Comment by jcoyne** [comment]
@elrayle also note that this was actually removed last week https://github.com/projecthydra-labs/hydra-works/pull/216  Do you need that PR reverted?
