### ISSUE TITLE
move full text extraction to hydra:derivatives

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#220]
It is desirable to have all derivative generation code in [hydra:derivatives](https://github.com/projecthydra/hydra-derivatives) to create a single API for generating derivatives.  This allows for the generation of derivatives to be configured by filetype in #makes_derivatives in file [derivatives.rb](https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/generic_file/derivatives.rb).

The process for a hydra-works based app to override #makes_derivatives needs to be defined and documented.

This will likely replace the service oriented approach for derivatives including Hydra::Works::GenerateThumbnail and proposed Hydra::Works::GenerateExtractedText (see PR https://github.com/projecthydra-labs/hydra-works/pull/213).  

QUESTIONS: 
Looking at Hydra::Works::GenerateThumbnail, `object.build_thumbnail` is called prior to calling `object.create_derivatives`.  
* Do files need to be created prior to calling #create_derivatives for all potential derivatives?  
* How would the app know which files (e.g. #build_thumbnail, #build_extracted_text) to create since it may vary based on the generic file's  primary content type?  
* Is it possible to do this automatically based on the configuration of setup in #make_derivatives

**Comment by elrayle** [comment]
Related discussion in issue https://github.com/projecthydra-labs/hydra-works/issues/215

**Comment by jcoyne** [comment]
I'm for moving full text extraction to hydra derivatives.  Please note that `makes_derivatives` has already been removed from the API.  I think the `object.build_*` belongs in the output file service that you pass to the Hydra::Derivatives Runner.

**Comment by jcoyne** [comment]
Closed by #228
