### ISSUE TITLE
adding a file_set to a collection is allowed and shouldn't be

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#257]
To reproduce...
```
col = Hydra::Works::Collection.new(id: 'col-1')
fs = Hydra::Works::FileSet.new(id: 'fs-1')

col.members << fs
=> [#<Hydra::Works::FileSet id: "fs-1", head: [], tail: []>]
```

Should throw an error message.  Instead, it incorrectly adds the file set to the collection.

**Comment by mjgiarlo** [comment]
@tpendragon @jcoyne Are you aware of any mechanisms we already have in place that would allow us to specify what kinds of things are allowed to be added to the `members` aggregation of `Collection`, for instance.

**Comment by mjgiarlo** [comment]
I'm working on this one.
