### ISSUE TITLE
Destroying a GenericWork will not remove its proxies from ordered_members of its containers.

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra-labs/hydra-works#260]
FileSets have [code](https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/file_set_behavior.rb#L23) that automatically remove them from works when the FileSet is destroyed.

```ruby
w = Hydra::Works::GenericWork.create
f = Hydra::Works::FileSet.create
w.ordered_members << f
w.save
f.destroy
w.reload.ordered_member_proxies.to_a.count # => 0 as expected
w.ordered_member_ids # => [] as expected
w.ordered_members.to_a # => [] as expected
```

Similar thing does not happen when you destroy a GenericWork. Empty proxies are left in any containing objects.

```ruby
c = Hydra::Works::Collection.create
w = Hydra::Works::GenericWork.create
c.ordered_members << w
c.save
w.destroy
c.reload.ordered_member_proxies.to_a.count # => 1
c.ordered_member_ids # => [nil]
c.ordered_members.to_a # => [nil]
```

I was also wondering if there's a reason why the code to automatically remove proxies of deleted objects isn't in hydra-pcdm or maybe activefedora-aggregations instead? Seems like you should be able to use Hydra-PCDM without Hydra-works, and have the redundant proxies be removed automatically.

**Comment by tpendragon** [comment]
It would probably take some convincing for me to agree to it in AF::Aggregations (seems like you'd have to make some problematic assumptions about what's being aggregated), but it probably makes sense in Hydra::PCDM. I think it hasn't been done in the past because of performance concerns.
