### ISSUE TITLE
Ordered file sets should go away.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#279]
https://github.com/projecthydra-labs/hydra-works/blob/1ac8be27dc09d03d90b8ec06b5f11d73ff541674/lib/hydra/works/models/concerns/work_behavior.rb#L54

At LDCX, those present agreed, that if you need ordered things (Pages for example), you should have a Page model.  FileSets should be unordered members of Works.

**Comment by mcritchlow** [comment]
:+1: on our end.

**Comment by barmintor** [comment]
if Collections gain the ability to aggregate FileSet, are they ordered in the same list as the Works?

**Comment by jcoyne** [comment]
@barmintor Collections do not aggregate FileSet, do they?

**Comment by barmintor** [comment]
We were talking about rolling that restriction back cc: @mjgiarlo
