### ISSUE TITLE
GenericCollection has files() interface

### ISSUE THREAD

**Issue by azaroth42** [projecthydra-labs/hydra-works#32]
Issue: generic_collection lacks files() interface but a collection can have associated files.

**Comment by flyingzumwalt** [comment]
This impacts #20

**Comment by flyingzumwalt** [comment]
Correction: Does this impact projecthydra-labs/hydra-pcdm#20?

**Comment by azaroth42** [comment]
Not sure what the issue is particularly, but pcdm:Collection only has
related objects, not files directly.  So in PCDM, a collection *should*
lack a files() interface.

On Mon, May 4, 2015 at 1:54 PM, flyingzumwalt <notifications@github.com>
wrote:

> Correction: Does this impact projecthydra-labs/hydra-pcdm#20
> <https://github.com/projecthydra-labs/hydra-pcdm/issues/20>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projecthydra-labs/hydra-works/issues/32#issuecomment-98847194>
> .
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by flyingzumwalt** [comment]
Based on @azaroth42's comment this is either resolved or irrelevant.  Closing it.
