### ISSUE TITLE
Allow addressing of segments of files as Works

### ISSUE THREAD

**Issue by azaroth42** [projecthydra-labs/hydra-works#34]
Although deferred at the F2F in Portland, there are use cases that require the addressing of segments of files as Works.  Some examples include:

 * An audio CD ripped to a single file, with offsets as to the tracks or other segmentation.
 * A digitized image that depicts two pages in a spread, and there is metadata about the individual pages
 * The division of a video of a musical performance based on different bands playing at different times

This requires multiple Works to be associated with parts of the same File.  To use the book case, there would be one Work for each page, and each page would need to refer to the segment of the File that depicts it.  If there are URIs for the Files, then fragment URIs could be used to refer to the areas.  
The larger question is about the use of hasFile ... which of the two pages has the file?  They can't both have it as that would break the files-associated-with-exactly-one-work rule.

**Comment by flyingzumwalt** [comment]
Please finish this sentence:   "This ticket is ready to be closed when..."  Maybe this information should be preserved somewhere?

**Comment by escowles** [comment]
This ticket is ready to be closed when there is a spec for referring to a section of a file.  I've added this to the agenda of the next Metadata Working Group meeting (5/6): https://wiki.duraspace.org/display/hydra/Copy+of+Metadata+Call+2015-05-06

**Comment by mjgiarlo** [comment]
@escowles has this been addressed yet?

**Comment by escowles** [comment]
@mjgiarlo: no, but it's been added to the todo list of the [structural metadata subgroup](https://wiki.duraspace.org/display/hydra/Structural+Metadata+Subgroup) of the Hydra Metadata Working Group, so I think we'll be talking about that shortly.

**Comment by azaroth42** [comment]
Can it reuse the OA Selector approach? 
http://www.w3.org/TR/annotation-model/#selectors

**Comment by mjgiarlo** [comment]
@escowles :ok_hand:

**Comment by escowles** [comment]
@azaroth42 The OA Selectors look good -- is there a time-based selector?  That seems like one of the most common uses, but I don't see more than a passing mention of it in that doc.

**Comment by azaroth42** [comment]
Timed segments use the W3C media fragment approach as a fragment selector, or just on the URI of the resource directly if there's no other assertions to be made.
See:  http://www.w3.org/TR/media-frags/#naming-time

Or, as a Selector, written out in full:
```json
  {
    "@id": "http://example.org/sptarget1",
    "@type": "oa:SpecificResource",
    "source": "http://example.org/thing-with-segment",
    "selector": {
      "@id": "http://example.org/selector1",
      "@type": "oa:FragmentSelector",
      "value": "t=10,20",
      "conformsTo": "http://www.w3.org/TR/media-frags/"
    }
  }
```
Which is equivalent to `http://example.org/thing-with-segment#t=10,20` but lets you make more assertions about the different components.

**Comment by jlhardes** [comment]
+1 to W3C media fragments for time-based selectors from the Avalon folks! OA Selectors sounds like a good approach to investigate for file segments.

**Comment by azaroth42** [comment]
Feel free to tag me in on any discussions in this space :)

**Comment by escowles** [comment]
I think the W3C media fragments and OA Selectors look very promising.  I've updated the Hydra structural metadata group wiki page to include links to those instead of making people read this whole discussion.

**Comment by barmintor** [comment]
"instead of making people read this whole discussion." <- at the end of the discussion

**Comment by escowles** [comment]
Closing this issue to avoid frustrating more people.  This work is now being done by the Hydra Metadata Interest Group [Segment of a File/Structural Metadata Working Group](https://wiki.duraspace.org/display/hydra/Segment+of+a+File+Structural+Metadata+Working+Group).
