### ISSUE TITLE
Should hydra:contains actually be a nested node in Fedora 4?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#38]
For example, the GenericWork hasFile predicate is a sub-property of hydra:contains. Should we model this in Fedora-4 by placing the file resource at a subpath of the work?

**Comment by terrellt** [comment]
I'm ambivalent. It seems like it fits the data model, so I'd be okay with it assuming we still have the relationships set up appropriately and don't just assume a relationship based on path. Does it help things somehow, or just easier for a human to recognize how it's related?

**Comment by jcoyne** [comment]
If we nest the files, Fedora-4 would automatically give us an "ldp:contains" assertion on the Work and "fedora:hasParent" assertion on the File

**Comment by awead** [comment]
It seems like there isn't any harm in doing this and there's some added benefits, such as what @jcoyne mentions, so I'm :+1: on this. However, should it be extended to Collection, which also utilizes hasFile, and is there any impact if a file can be a part of more than one work or collection? Would we want to, or are we able to, do this to hasMember as well?

**Comment by azaroth42** [comment]
I need to work through it before commenting in any meaningful way. There's some snarly bits with the relationships between LDP and ORE that might make things trickier than they appear, especially when proxy nodes are part of the mix.  I'll try to grab @cbeer this afternoon...

**Comment by azaroth42** [comment]
Clearly I did not manage to do that. We should discuss in detail at the post-code4lib hydra meeting IMO.

**Comment by azaroth42** [comment]
Proposal to discuss:
https://docs.google.com/document/d/1RI8aX8XQEk-30-Ht-DaPF5nz_VtI1-eqxUuDvF3nhv0/edit

**Comment by flyingzumwalt** [comment]
Is this resolved?
