### ISSUE TITLE
Update README and Guidelines for Contributing to reflect current developments

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#53]
The [README](https://github.com/projecthydra-labs/hydra-works/blob/master/README.md) is incomplete and out of date.  It needs to 
- [x] Declare what functionality is provided by the gem
- [x] Declare the intended uses of the gem
- [x] Declare the relationship between this code and Sufia, sufia-models, Worthwhile and Curate
- [x] Provide Instructions for Installation/Use 
- [x] Provide links to background documentation (ie. Application Profile) with context explaining the relationship between that documentation and this code

The  [Guidelines for Contributing](https://github.com/projecthydra-labs/hydra-works/blob/master/CONTRIBUTING.md) still say that we are soliciting Use Cases.  They don't say anything about contributing code or submitting issues other than Use Cases.  They should
- [x] Provide guidelines for contributing code
- [x] Provide guildelines for submitting issues and pull requests
Is there a template for this somewhere in the Hydra space?  If not, should we create one and apply it to all of the repositories?

**Comment by flyingzumwalt** [comment]
@mjgiarlo can you help me with the first three points for the README?  Also, any ideas on the Guidelines for Contributing?

**Comment by mjgiarlo** [comment]
@flyingzumwalt 

Re: guidelines, we should be able to copy what's in the main Hydra repo: https://github.com/projecthydra/hydra/blob/master/CONTRIBUTING.md

About the README, I should have time later to drop some text in here.  Cool?

**Comment by flyingzumwalt** [comment]
Is there anything you want me to write for the README, or is it easier for
you to just write it all from the perspective of a consumer (sufia)?

I'll copy the Contributions Guidelines.

On Tue, May 5, 2015 at 11:58 AM, Michael J. Giarlo <notifications@github.com

**Comment by mjgiarlo** [comment]
@flyingzumwalt If you could take a crack at the two bullets starting with "provide," that'd be great.  And I'll have at the "declare" bullets.

**Comment by flyingzumwalt** [comment]
FYI @mjgiarlo I added a skeleton README on the [53-update_readme](https://github.com/projecthydra-labs/hydra-works/tree/53-update_readme) branch

**Comment by mjgiarlo** [comment]
OK, I moved my blocker out of the way and will have time for this tomorrow. Sorry for the delay!

**Comment by flyingzumwalt** [comment]
I've done the basic "Provide" bullets,  so @mjgiarlo reassigning the ticket for you to finish.  Note: PR #54 has the contribution guidelines

**Comment by mjgiarlo** [comment]
Thx, @flyingzumwalt -- I'll take a crack at this momentarily.

**Comment by mjgiarlo** [comment]
OK, I have time to do this today!
