### ISSUE TITLE
Start Sufia pcdm integration and report bugs

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#55]
Within the [pcdm-integration branch](https://github.com/projecthydra/sufia/tree/pcdm-integration) of sufia, 

- [x] run the tests with pcdm & hydra-works as dependencies, look through the failures and record tickets for any flaws in pcdm and hydra-works that it kicks up.
- [ ] start refactoring sufia to use hydra works GenericFile and GenericWork

**Comment by flyingzumwalt** [comment]
Ignore the second bullet point.  That will be covered by #60.  You can close this if the pcdm-integration branch has all of its tests passing.

**Comment by kevinreiss** [comment]
Okay. That branch is green on Travis. Closing.
