### ISSUE TITLE
Remove redundant declaration of PCDM predicates in hydra-works

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#56]
hydra-pcdm defines PCDMTerms here: https://github.com/projecthydra-labs/hydra-pcdm/blob/master/lib/hydra/pcdm/vocab/pcdm_terms.rb

Does that mean this code in hydra-works redundant? https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works.rb#L10-L24

**Comment by jcoyne** [comment]
Yes, that code is redundant and should be removed.
