### ISSUE TITLE
GenericWork has GenericFiles as members and persists as a PCDM Object

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#57]
Reference: [Hydra Works PCDM Diagram](https://docs.google.com/drawings/d/1-NkkRPpGpZGoTimEpYTaGM1uUPRaT0SamuWDITvtG_8/edit?usp=sharing)

Related to #58, #59

**Comment by flyingzumwalt** [comment]
This set of sample RDF objects might be useful reference when you review this work, or might inform what's in your tests.  The objects you create in Fedora should look like the ones @awead created here https://github.com/awead/sufia-pcdm

**Comment by kevinreiss** [comment]
Being worked on in https://github.com/projecthydra-labs/hydra-works/tree/gen_work_has_gen_files
