### ISSUE TITLE
[Integration] Update Sufia to rely on the 3 Hydra::Works classes

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#60]
- [x] Update Sufia GenericFile, GenericWork and Collection to be subclasses of the corresponding Hydra::Works classes.  
- [x] Report on any bugs this causes if they require changes in hydra-works or hydra-pcdm
- [x] If the Sufia test suite passes with this integration, submit a PR to Sufia 

**Note** If this integration triggers necessary changes in sufia or sufia-models, record the tickets in that repository, not here.

**Comment by flyingzumwalt** [comment]
Depends on #57, #58 and #59.

**Comment by grosscol** [comment]
I'll take a stab at this.

**Comment by jcoyne** [comment]
@grosscol I just saw your message on here. I've also been working on this. Are you on IRC this morning?

**Comment by jcoyne** [comment]
Blocked by projecthydra/sufia#1130 and projecthydra/sufia#1127

**Comment by jcoyne** [comment]
Lynette said this is a good integration branch: https://github.com/projecthydra-labs/hydra-works/tree/bring_works_inline_with_pcdm.

**Comment by flyingzumwalt** [comment]
## Where to look
This work is being done on sufia's [real_integration](https://github.com/projecthydra/sufia/tree/real_integration) branch of sufia and is currently blocked by a [failure](https://travis-ci.org/projecthydra/sufia/jobs/62425558) on sufia's [af-master](https://github.com/projecthydra/sufia/tree/af_master) branch

**Comment by flyingzumwalt** [comment]
The relevant pull request: projecthydra/sufia#1149

**Comment by jcoyne** [comment]
Final sufia PR (with collections) https://github.com/projecthydra/sufia/pull/1168

**Comment by flyingzumwalt** [comment]
:thumbsup:
