### ISSUE TITLE
Hydra::Works::Collection Behaviors

### ISSUE THREAD

**Issue by kevinreiss** [projecthydra-labs/hydra-works#68]
The points below are from @elrayle original comments in code. I took out a reference Hydra::Works::File since that class is something that we decided not implement. Which of these are behaviors that actually need to be implemented in hydra-works?

* [ ] Hydra::Works::Collection can NOT aggregate Hydra::PCDM::Collection unless it is also a Hydra::Works::Collection

* [ ] Allow Collection to have both GenericWorks and Collections as members

**Comment by awead** [comment]
@kevinreiss I think these are covered in projecthydra-labs/hydra-pcdm#23

**Comment by kevinreiss** [comment]
I left one up from the original list that seems like it is relevant for hydra-works.

**Comment by eliotjordan** [comment]
Working on this in https://github.com/projecthydra-labs/hydra-works/tree/gen_work_has_gen_files.  Will watch for what happens in #72 based on bug report in #71.

**Comment by kevinreiss** [comment]
Subsumed by #77.
