### ISSUE TITLE
Hydra::Works::GenericWork Behaviors

### ISSUE THREAD

**Issue by kevinreiss** [projecthydra-labs/hydra-works#69]
The points below are from @elrayle original comments in code. I took out a reference Hydra::Works::File since that class is something that we decided not implement. Which of these are behaviors that actually need to be implemented in hydra-works?

* [ ] Hydra::Works::GenericWork can NOT aggregate Hydra::PCDM::Collection
* [ ] Hydra::Works::GenericWork can NOT aggregate Hydra::Works::Collection
* [ ] Hydra::Works::GenericWork can NOT aggregate Works::GenericWork unless it is also a Hydra::Works::GenericFile
* [ ] Hydra::Works::GenericWork can aggregate Hydra::Works::GenericFile
* [ ] Allow GenericWork to have both GenericWorks and GenericFiles as members

**Comment by awead** [comment]
@kevinreiss also covered in projecthydra-labs/hydra-pcdm#23 but you'd probably want integration tests here to verify that?

**Comment by eliotjordan** [comment]
Working on this in https://github.com/projecthydra-labs/hydra-works/tree/gen_work_has_gen_files.  Will watch for what happens in #72 based on bug report in #71.

**Comment by kevinreiss** [comment]
Subsumed by #77.
