### ISSUE TITLE
Hydra::Works::GenericFile Behaviors

### ISSUE THREAD

**Issue by kevinreiss** [projecthydra-labs/hydra-works#70]
The points below are from @elrayle original comments in code. I took out a reference Hydra::Works::File since that class is something that we decided not implement. Which of these are behaviors that actually need to be implemented in hydra-works?

* [ ] Hydra::Works::GenericWork can NOT aggregate Hydra::PCDM::Collection
* [ ] Hydra::Works::GenericWork can NOT aggregate Hydra::Works::Collection
* [ ] Hydra::Works::GenericWork can NOT aggregate Works::GenericWork unless it is also a Hydra::Works::GenericFile
* [ ] Hydra::Works::GenericWork can aggregate Hydra::Works::GenericFile

**Comment by eliotjordan** [comment]
Working on this in https://github.com/projecthydra-labs/hydra-works/tree/gen_work_has_gen_files.  Will watch for what happens in #72 based on bug report in #71.

**Comment by kevinreiss** [comment]
subsumed by #77.
