### ISSUE TITLE
Work generic_file validation is wrong

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#71]
https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/concerns/work_behavior.rb#L41-L42

it is validating that the type of file must be a Works::GenericFile however Sufia will want to provide a "GenericFile" which does not satisfy the current validation:

```
     ArgumentError:
       each file must be a Hydra::Works::GenericFile
```

**Comment by jcoyne** [comment]
See https://travis-ci.org/projecthydra/sufia/jobs/62100942

**Comment by jcoyne** [comment]
Blocked by #72

**Comment by elrayle** [comment]
I have a fix for this specific problem.  I will create a PR.

**Comment by elrayle** [comment]
PR https://github.com/projecthydra-labs/hydra-works/pull/74 fixes this issue.  When the PR is merged, this ticket should be closed.

**Comment by elrayle** [comment]
To validate something is a generic file...
```
raise ArgumentError, "parent_generic_file must be a works generic file" unless Hydra::Works.generic_file? parent_generic_file
```

**Comment by elrayle** [comment]
I realized that the tests for Hydra::Works is not extensive enough to verify the basic behavior of collections, generic_works, and generic_files.  I am adding tests equivalent to those at the Hydra::PCDM level.  See https://github.com/projecthydra-labs/hydra-works/issues/77.

**Comment by elrayle** [comment]
Ok, with the fuller set of tests, it is apparent the kludge does not work.  By using initialize method, it is not fully using the included PCDM:CollectionBehavior.  It does not seem to create the members container in Fedora.  The most common error:
```
NoMethodError:
       undefined method `container' for []:ActiveFedora::Associations::ContainerProxy
```

**Comment by kevinreiss** [comment]
Why do we want to use:

```
all_members = self.members.container.to_a
```

instead of just:

```
all_members = self.members.to_a
```

**Comment by elrayle** [comment]
Fixed by PR https://github.com/projecthydra-labs/hydra-pcdm/pull/85
