### ISSUE TITLE
service: upload to generic file

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#72]
# Upload a file to a generic file, optionally running auto-generation services to create variants.
    #
    # @param [Hydra::Works::GenericFile] :generic_file into which to upload the file
    # @param [String] :path_to_file path to the file being uploaded
    # @param [Hash] :auto_gen_services info for auto-generating files from the uploaded content file
    #
    # @return [Hydra::Works::GenericFile] the updated generic file

Questions:
* A generic_file is defined as one content file + variants that are auto-generated.  Do others agree?
* If the generic_file already has files, is the new file considered a new version of the existing content file?
* What predicate should be used for identifying the purpose of the uploaded content file and each auto-gen file?  (e.g. use - what is the full URI?)
* What values should be used for the 'purpose' predicate?  (e.g. file.use = "content" | "thumbnail" | "extracted_text")

This was https://github.com/projecthydra-labs/hydra-pcdm/issues/74

**Comment by elrayle** [comment]
add to the examples in README once working

**Comment by elrayle** [comment]
Working on this in branch...  https://github.com/projecthydra-labs/hydra-works/tree/upload_file_to_gfile

**Comment by awead** [comment]
fixed in #105
