### ISSUE TITLE
Add tests for collections, generic_works, and generic_files

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#77]
Write tests equivalent to those in PCDM for each of the models in HydraWorks.

**Comment by kevinreiss** [comment]
This ticket probably can likely close out #68, #69, #70. We can just double-check that any individual points broken out there have been hit.

**Comment by elrayle** [comment]
Fixed by PR https://github.com/projecthydra-labs/hydra-works/pull/96
