### ISSUE TITLE
Provide a definition of scope of "Work"?

### ISSUE THREAD

**Issue by azaroth42** [projecthydra-labs/hydra-works#8]
My understanding is that it is a compound or complex object (eg a resource that has parts, which may themselves have parts).  It is not the bibliographic notion of an abstract Work (as opposed to a physical Item that embodies the Work).  

It would be good to come to a common understanding of the definition and thus scope of the effort __before__ starting in on modeling.

**Comment by jeremyf** [comment]
I believe we can call this closed. Let it be henceforth known as [PCDM](https://github.com/projecthydra-labs/hydra-pcdm)
