### ISSUE TITLE
Test that triples are correctly set in fedora objects

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-works#85]
Right now, the tests validate behaviors.  There are no tests that validate that expected predicates and values are set in the fedora object.

Ex. 
* Are generic works associated with a collection via the pcdm:hasMember predicate?
* Are related objects associated with an collection via the ore:aggregates predicate?
etc.

**Comment by jcoyne** [comment]
I think those tests should exist in hydra-PCDM or AF-aggregation or active fedora itself. I don't think we need to cover all that again here.

**Comment by elrayle** [comment]
I think that is fine, as long as it is getting covered.  Do you want to add this to AF-aggregator, or should it live at hydra-PCDM?

**Comment by jcoyne** [comment]
It's already tested in AF-aggregator here: 
https://github.com/projecthydra-labs/activefedora-aggregation/blob/6a07c77db6798fbaeb55d3147aac6ce85553f3cc/spec/activefedora/association_spec.rb#L186-L189
