### ISSUE TITLE
Move file Characterization from Sufia to Hydra::Works

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#89]
Move Sufia::GenericFile::Characterization to Hydra::Works::File::Characterization

**Comment by flyingzumwalt** [comment]
@jcoyne during the sprint it sounded like this was going to necessarily come along with #90 (Derivative Generation) but I don't see it in the code base anywhere.  Was it ruled out?  If so, I need to move it into curation_concerns.

**Comment by jcoyne** [comment]
@flyingzumwalt No idea. Is there some reason you're asking me?

**Comment by awead** [comment]
@flyingzumwalt I decided to punt on characterization because it was a bit much at the time and required getting FITS in the mix. Also, we haven't mapped out FITS to RDF yet, which I think should happen when we add the characterization service to hydra-works.

**Comment by mjgiarlo** [comment]
@awead And that work is coming along, but not yet done: sufia#1006

**Comment by escowles** [comment]
@mjgiarlo Any progress on https://github.com/projecthydra/sufia/issues/1006 since the flurry of discussion about the RDF vocab in early June?  As long as we're moving characterization down into hydra-works, it seems like a good time to RDF-ify it too.

**Comment by mjgiarlo** [comment]
@escowles In light of a potential discussion about related files at next week's Hydra Tech call, and some reticence from folks about the utility of RDFifing FITS output, I was hoping to abandon the effort, tbh. I'm planning to re-assess after we discuss related files. If you have a particular interest in RDF-ifying FITS output, though, I don't think there's any real downside to it, and I'd be happy to hand it off. Your call?

**Comment by mjgiarlo** [comment]
Planning to include this in a version > 0.1 of Hydra-works.

**Comment by mjgiarlo** [comment]
@grosscol is working on this, I believe.

**Comment by jcoyne** [comment]
Currently work on this is in https://github.com/projecthydra-labs/hydra-works/issues/209

**Comment by mjgiarlo** [comment]
@jcoyne @grosscol Can this be closed? If so, lines 48 and 165 could use some attention here: https://github.com/projecthydra-labs/curation_concerns/blob/master/spec/controllers/curation_concerns/file_sets_controller_spec.rb

**Comment by grosscol** [comment]
Made a new issue for the pending specs: projecthydra-labs/curation_concerns#373
