### ISSUE TITLE
Files have accessors for .content and .thumbnail

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#92]
This replaces the functionality from Sufia::GenericFile::Content 

If this belongs further up the stack, that's fine.  I'm just making tickets for each row in the CodeShredding document.

**Comment by awead** [comment]
@flyingzumwalt how does this work if there are multiple GenericFiles attached to the work?

**Comment by flyingzumwalt** [comment]
@awead That was a typo.  These methods are File behaviors, not Work behaviors.

**Comment by awead** [comment]
@flyingzumwalt oh, good then. I added that here e43efc5512b086ff24b4484ca45c388811c8d2cb except that `content` is `original_file` in Hydra::Works. I think Sufia should delegate its own `content` method to that. What do you think?

**Comment by flyingzumwalt** [comment]
:+1: to Sufia delegating its `content` method to `original_file`
