### ISSUE TITLE
Move support for File Versioning from Sufia to Hydra::Works

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#93]
Move Sufia::GenericFile::Versions to Hydra::Works::File::Versions

**Comment by awead** [comment]
see todo in [Hydra::Works::AddVersionedOriginalFile](https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/services/object/add_versioned_original_file.rb)

**Comment by escowles** [comment]
This was resolved with https://github.com/projecthydra-labs/hydra-works/commit/c01fa0f2f7cabc23a8e7ea664f92f07ce43a8652
