### ISSUE TITLE
Move Virus Checking functionality from Sufia to Hydra::Works

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#94]
Move Sufia::GenericFile::VirusCheck to Hydra::Works::File::VirusCheck

**Note**: Provide this in hydra-works but make it optional -- don't include in FileBehaviors

**Comment by escowles** [comment]
The other half of this (making curation_concerns use the updated hydra-works) is tracked in https://github.com/projecthydra-labs/curation_concerns/issues/37
