### ISSUE TITLE
Move Indexing and Full Text Indexing support from Sufia to Hydra::Works

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#95]
- [x] ~~Move Sufia::GenericFile::Indexing to Hydra::Works::File::Indexing~~
- [x] ~~Move Sufia::GenericFile::FullTextIndexing to Hydra::Works::File::FullTextIndexing~~

See below

Related to #89 and #90

**Comment by awead** [comment]
see e43efc5512b086ff24b4484ca45c388811c8d2cb for attaching extracted text to the file.

**Comment by jpstroop** [comment]
Following 8/5 conference call, see projecthydra-labs/curation_concern#142. The [full text extraction service](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/services/curation_concerns/full_text_extraction_service.rb) should be moved here, but it should not be called anywhere. Indexing should take place upstream (e.g. in CurationConcerns or custom apps). Reciprocal issue in CurationConcerns is projecthydra-labs/curation_concerns#141

**Comment by mjgiarlo** [comment]
https://github.com/projecthydra-labs/hydra-works/pull/195
